### ISSUE TITLE
rofl-docs: Document `podman-compose` caveats

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/oasis-sdk#2164]
I tripped up on these two issues:
- https://github.com/containers/podman-compose/issues/264: While this works in `docker compose`:

```yaml
services:
  oracle:
    environment:
      CONTRACT_ADDRESS: 0x5FbDB2315678afecb367f032d93F642f64180aa3
    entrypoint: /bin/sh -c 'python main.py --network http://sapphire-localnet:8545 --ollama-address http://ollama:11434 --secret 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 $${CONTRACT_ADDRESS}'
```

The `CONTRACT_ADDRESS` will be empty in `podman-compose`. Injecting the variable directly inside `entrypoint` seems to be the only way currently

```yaml
services:
  oracle:
    entrypoint: /bin/sh -c 'python main.py --network http://sapphire-localnet:8545 --ollama-address http://ollama:11434 --secret 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 0x5FbDB2315678afecb367f032d93F642f64180aa3'
```

- https://github.com/containers/podman-compose/issues/575: Waiting for containers to spin up in the correct order with `depends_on` directive doesn't work. So this `oracle`:

```yaml
  oracle:
    environment:
      CONTRACT_ADDRESS: 0x5FbDB2315678afecb367f032d93F642f64180aa3
    build:
      dockerfile: Dockerfile.oracle
        entrypoint: /bin/sh -c 'python main.py --network http://sapphire-localnet:8545 --ollama-address http://ollama:11434 --secret 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 $${CONTRACT_ADDRESS}'
    restart: on-failure
    depends_on:
      contracts:
        condition: service_completed_successfully
```

will be started prematurely before the contracts are deployed. Adding some `sleep` can solve the issue:

```yaml
  oracle:
    build:
      dockerfile: Dockerfile.oracle
    entrypoint: /bin/sh -c 'sleep 100; python main.py --network http://sapphire-localnet:8545 --ollama-address http://ollama:11434 --secret 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 0x5FbDB2315678afecb367f032d93F642f64180aa3'
    restart: on-failure
```

Document both caveats somewhere at the end of https://docs.oasis.io/build/rofl/app probably?
