### ISSUE TITLE
rofl-docs: Mention `service qgsd restart` in troubleshooting

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/oasis-sdk#2171]
There seems to be an annoying bug somewhere in `qgsd` (or somewhere in the ROFL middleware) where quotes are not valid anymore. Restarting the service `sudo service qgsd restart` helps. No need to restart the oasis node.

**Comment by kostko** [comment]
It is not that the quotes are not valid, but `qgsd` starts returning a zero-length quote (e.g. an empty quote) due to an "unknown network error" (`0xb011`) in the quote provider:
```
qgsd[1412990]: [QPL] Failed to get quote config. Error code is 0xb011
qgsd[1412990]: [get_platform_quote_cert_data ../td_ql_logic.cpp:302] Error returned from the p_sgx_get_quote_config API. 0xe044
qgsd[1412990]: tee_att_get_quote_size return 0x11001
```

**Comment by gw0** [comment]
Reported upstream:
- https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/450

Our current workaround in `docker-compose.yaml` to check the logs for error and restart (still testing):
```
    command: ["/opt/intel/tdx-qgs/qgs", "--no-daemon"]
    entrypoint: ["/bin/bash", "-c", "exec \"$0\" \"$@\" &> >(tee -a /tmp/qgsd.log)"]
    init: true
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "grep 'Error code is 0xb011' /tmp/qgsd.log && (: > /tmp/qgsd.log && kill -SIGTERM 1 && exit -1) || (: > /tmp/qgsd.log && exit 0)"]
      interval: 60s
      timeout: 2s
      retries: 0
```
