### ISSUE TITLE
rofl: IPs and ports offer in marketplace

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/oasis-sdk#2194]
The node configuration for enabling port forwarding (implemented in https://github.com/oasisprotocol/oasis-core/pull/6123) currently looks like this:

```yaml
runtime:
  runtimes:
  - id: 000000000000000000000000000000000000000000000000a6d1e3ebf60dff6c # Sapphire
    components:
    - id: rofl.rofl1qrqt8jhk2s9f60yshmgr7g4h9p6fmezkavedwxkz # demo-rofl-www
      networking:
        incoming:
        - ip: 192.168.0.3
          protocol: tcp
          src_port: 5555
          dst_port: 80
```

Which means port 5555 on the server will be mapped to port 80 inside ROFL.

Then in `compose.yaml` a developer always uses the same port regardless of where will ROFL be deployed:

```yaml
services:
  frontend:
    build:
      dockerfile: Dockerfile
    image: "ghcr.io/matevz/demo-rofl-www"
    ports:
      - "80:80"
```

In the marketplace, the provider may not know exactly which external IPs and ports will be available in advance, but he could offer the amount of those. I suggest the following flow:

1. The offer should contain:
   - a number of external static IPs v4 and/or v6 (usually 1, but there may be some providers without external IPs!)
   - a number of ports in a range for each IP (usually 10-ish)
2. In `rofl.yaml` the following should be added to resources:

```
  networking:
    ips_v4: number
    ips_v6: number
    ports: number
```

3. When a user decides to rent a machine, only offers that satisfy these resources should be considered.
4. When a user decides to rent a machine, he should receive the exact IP(s) and the specific range of ports for him.
5. During `oasis rofl build` the CLI can check, if the number of ports defined under resources satisfies ports exposed in `compose.yaml`
