### ISSUE TITLE
Support limiting query methods in config

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/oasis-sdk#858]
There's currently a single config setting, `allow_expensive_queries`. When `true`, it has a double effect:
1. Allows some queries to run that would otherwise return `Forbidden`; it's hardcoded which queries those are.
2. Causes `core.EstimateGas` to simulate smart contracts; otherwise, only the non-smart-contract parts of each tx are looked at for gas estimation.

Under 1, we don't want a hardcoded list. And we want to not lump 1 and 2 under the same flag.

**Comment by mitjat** [comment]
### Proposed API

The functionality of the old `allow_expensive_queries` will be split into `estimate_gas_by_simulating_contracts` and `forbidden_queries`.
We'll also add a related but completely new `max_estimated_gas` config value; see below.

This is what the new config would look like:
```yaml
# If false, the gas estimate by `core.EstimateGas` will not include the gas needed to execute
# any smart contracts in the tx. If `true`, `core.EstimateGas` will simulate executing the
# smart contract to derive a more accurate gas estimate. Default: false.
estimate_gas_by_simulating_contracts: <bool>  

# When estimating gas in `core.EstimateGas`, simulate the tx (and report) only up to this much
# used gas. This limit is more likely to be relevant if `estimate_gas_by_simulating_contracts` is
# enabled. The special value of 0 means that the maximum amount of gas in a batch will be
# used. Default: 0
max_estimated_gas: <number>

# A list of `<methodName>: <bool>` entries. Each entry indicates whether query `<methodName>`
# is allowed to run. The list is evaluated in an early-exit fashion: only the first matching entry is
# heeded. Two special values for `<methodName>` are supported: `all` matches all queries, and
# `all-expensive` matches all queries tagged `expensive` via `#[handler(query = "...", expensive)]`.
# The list implicitly ends with two invisible entries: `all-expensive: false` and `all: true`.
allowed_queries:
  - core.CheckInvariants: false
  # - all-expensive: false  # this line is always implicity present
  # - all: true             # this line is always implicity present
```

The above example for `allowed_queries` shows a config that disallows all expensive queries except `core.CheckInvariants`.

The following existing query handlers will be tagged `expensive`:
* core.CheckInvariants
* accounts.Addresses
* evm.SimulateCall
* contracts.Custom

These are also exactly the queries that currently perform the check `if !ctx.are_expensive_queries_allowed() { return Err(Error::Forbidden) }`.

This config is equivalent to the old `allow_expensive_queries: true`:
```yaml
estimate_gas_by_simulating_contracts: true
allowed_queries:
  - all-expensive: true
```

An empty config, i.e. sticking to defaults, is equivalent to the old `allow_expensive_queries: false`. Alternatively, the following more explicit config achieves the same:
```yaml
estimate_gas_by_simulating_contracts: false
allowed_queries:
  - all-expensive: false
  - all: true
```
