### ISSUE TITLE
cli: Add support for Request enum variants without params

### ISSUE THREAD

**Issue by formiat** [oasisprotocol/oasis-sdk#995]
Duplicated also here: https://github.com/oasisprotocol/oasis-cbor/issues/28

It will be more convenient to have opportunity to use `Request` enums with no params. Example:

```rust
#[derive(Clone, Debug, cbor::Encode, cbor::Decode)]
pub enum Request {
    #[cbor(rename = "instantiate")]
    Instantiate,

    <...>
}
```

This example doesn't work, because we receive error when we try to instantiate. None of these variants work:
`oasis contracts instantiate <code_id> 'instantiate'`
`oasis contracts instantiate <code_id> '{instantiate}'`
`oasis contracts instantiate <code_id> '{instantiate: {}}'`

We receive error: `Execution failed with error: module: contracts code: 12 message: execution failed: unreachable executed`

**Comment by kostko** [comment]
Just checking -- what version of the CLI are you using?

**Comment by formiat** [comment]
Here are lines from my `Cargo.toml`. Is it enough?

```toml
[dependencies]
cbor = { version = "0.2.1", package = "oasis-cbor" }
oasis-contract-sdk = { git = "https://github.com/oasisprotocol/oasis-sdk" }
oasis-contract-sdk-storage = { git = "https://github.com/oasisprotocol/oasis-sdk" }
```
